CREATE DATABASE DANG_KY_MON_HOC;
GO

USE DANG_KY_MON_HOC;
GO

CREATE TABLE HOCKY (
	MaHocKy CHAR(9) NOT NULL, --HK1_22-23, HK2_22-23,..
	NgayKhaiGiang DATE NOT NULL, 
	NgayBeGiang DATE NOT NULL,
	CONSTRAINT PK_HOCKY PRIMARY KEY (MaHocKy),
);
GO

CREATE TABLE KHOA (
	MaKhoa VARCHAR(5) NOT NULL, --FIT, FCFT, FCEAM, ITE,...
	TenKhoa NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_KHOA PRIMARY KEY (MaKhoa),
);
GO

CREATE TABLE GIANGVIEN (
	MaGiangVien CHAR(6) NOT NULL, --GV0001, GV0002,...
	HoTen NVARCHAR(MAX) NOT NULL,
	HocVi NVARCHAR(10) NOT NULL, --Thạc sĩ, Tiến sĩ, Cử nhân,...
	HocHam NVARCHAR(12), --Phó Giáo sư, Giáo sư
	DiaChi NVARCHAR(MAX),
	Sdt CHAR(10) CHECK(len(Sdt) = 10) NOT NULL,
	MaKhoa VARCHAR(5) NOT NULL,
	CONSTRAINT PK_GIANGVIEN PRIMARY KEY (MaGiangVien),
	CONSTRAINT FK_GIANGVIEN_KHOA FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa),
);
GO

CREATE TABLE MONHOC (
	MaMon CHAR(10) NOT NULL, --WEPR330479, DBMS330284,...
	TenMonHoc NVARCHAR(30) NOT NULL,
	SoTinChi INT NOT NULL, --(từ 1 đến 4)
	MaKhoa VARCHAR(5) NOT NULL, --FIT, FCFT, FCEAM, ITE,...
	CONSTRAINT PK_MONHOC PRIMARY KEY (MaMon),
	CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa),
);
GO

CREATE TABLE HOCVIEN (
	MaHocVien CHAR(10)  NOT NULL, --HV00000001, HV00000011,...
	HoTen NVARCHAR(40) NOT NULL, --Lê Hoàng Hiếu Nghĩa Đệ Nhất Thương Tâm Nhân (tên dài nhất VN),...
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(MAX) NOT NULL,
	QueQuan NVARCHAR(20) NOT NULL, --Bà Rịa - Vũng Tàu, Thừa Thiên - Huế,...
	MaKhoa VARCHAR(5) NOT NULL, --FIT, FCFT, FCEAM, ITE,...
	CONSTRAINT PK_HOCVIEN PRIMARY KEY (MaHocVien),
	CONSTRAINT FK_HOCVIEN_KHOA FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa),
);
GO

CREATE TABLE PHONGHOC (
	MaPhong VARCHAR(10) NOT NULL, --A5-203, A121, B108
	LoaiPhong NVARCHAR(40) NOT NULL, --Phòng lý thuyết, Phòng máy tính, Phòng thực hành, Phòng thí nghiệm,...
	CONSTRAINT PK_PHONGHOC PRIMARY KEY (MaPhong),
);
GO

CREATE TABLE LOPHOC (
	MaLop CHAR(18) NOT NULL, --DBMS330284_23_1_05, WEPR330479_23_1_11
	TenLop NVARCHAR(MAX) NOT NULL, 
	MaGiangVien CHAR(6) NOT NULL, --GV0001, GV0002,...
	MaMon CHAR(10) NOT NULL, --WEPR330479, DBMS330284,...
	MaHocKy CHAR(9) NOT NULL, --HK1_22-23, HK2_22-23,..
	SoHocVienDangKy INT NOT NULL CHECK (SoHocVienDangKy <= 75),
	MaPhong VARCHAR(10) NOT NULL, --A5-203, A121, B108
	Thu NVARCHAR(10) NOT NULL,
	Tiet NVARCHAR(10) NOT NULL,
	CONSTRAINT PK_LOPHOC PRIMARY KEY (MaLop),
	CONSTRAINT FK_LOPHOC_GIANGVIEN FOREIGN KEY (MaGiangVien) REFERENCES GIANGVIEN(MaGiangVien),
	CONSTRAINT FK_LOPHOC_MONHOC FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMon),
	CONSTRAINT FK_LOPHOC_HOCKY FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy),
	CONSTRAINT FK_LOPHOC_PHONGHOC FOREIGN KEY (MaPhong) REFERENCES PHONGHOC(MaPhong),
);
GO

CREATE TABLE DKMH (
	MaHocVien CHAR(10) NOT NULL,
	MaLop CHAR(18) NOT NULL,
	CONSTRAINT PK_DKMH PRIMARY KEY (MaHocVien, MaLop),
	CONSTRAINT FK_DKHP_LOPHOC FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop),
	CONSTRAINT FK_DKHP_HOCVIEN FOREIGN KEY (MaHocVien) REFERENCES HOCVIEN(MaHocVien),
);
GO

CREATE TABLE YEUCAU (
	MaGiangVien CHAR(6) NOT NULL,
	MaMon CHAR(10) NOT NULL,
	SoHocVienDuocDangKy INT NOT NULL,
	CONSTRAINT PK_YEUCAU PRIMARY KEY (MaGiangVien, MaMon),
	CONSTRAINT FK_YEUCAU_GIANGVIEN FOREIGN KEY (MaGiangVien) REFERENCES GIANGVIEN(MaGiangVien),
	CONSTRAINT FK_YEUCAU_MONHOC FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMon),
);
GO

CREATE TABLE TAIKHOAN (
    TaiKhoan NVARCHAR(10) NOT NULL,
    MatKhau NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_TAIKHOAN_TAIKHOAN PRIMARY KEY (TaiKhoan)
);
GO
